### ISSUE TITLE
App auto closes when adding an account.  

### ISSUE THREAD

**Issue by Nambomb** [robotswingset/narwhal-bugs#21]
When I add an account and the page after I login, I click accept and it automatically crashes the app.  Not sure what to do to add the account.

**Comment by zpolozune** [comment]
I also had this happen, but in addition I had an account already added and when I tried to switch to it it failed. After removing the account as instructed and upon attempting to readd the removed account the app crashes as soon as the OAuth authentication starts.

**Comment by aptkingston** [comment]
Same issue here. Appears to be related to adding account that has already been used.

My exact steps:
- Signed in and using account A, fully working
- Add new account B, which requires signing out of account A as instructed
- Now signed in and using account B, fully working
- Attempt to swap back to account A which fails with a retry message. Eventually gave up retrying, so deleted account A from the app
- Attempt to add account A as a new account. Sign in works, and you get pushed to the permission screen to accept Narwhal's access
- Pressing accept will now crash the app after the oauth redirect, and the account does not get added

Edit: @Nambomb @zpolozune this bug can be fixed by uninstalling the app and installing it again. With a fresh install you'll be able to add the account successfully.

**Comment by 2carlos** [comment]
For me, Uninstall + reinstall worked for about a week before issue returned.

**Comment by ilyanep** [comment]
I’m also seeing this issue, with the same behavior 2carlos describes. 

Moreover, this behavior is often associated with other parts of the app acting as if I’m not logged in (eg home page shows default subs, can’t upvote, etc)

**Comment by rickharrison** [comment]
Thanks for these bug reports y'all. This was an issue with the Reddit API, but I've been able to engineer around it. Fix coming very soon.
